<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ModelContextProtocol.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LifeGraph.Infrastructure\LifeGraph.Infrastructure.csproj" />
    <ProjectReference Include="..\LifeGraph.Http\LifeGraph.Http.csproj" />
    <ProjectReference Include="..\LifeGraph.Accounts\LifeGraph.Accounts.csproj" />
    <ProjectReference Include="..\LifeGraph.Graph\LifeGraph.Graph.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="LifeGraph.UnitTests" />
    <InternalsVisibleTo Include="LifeGraph.IntegrationTests" />
  </ItemGroup>

</Project>
