// <auto-generated />
using System;
using LifeGraph.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LifeGraph.Migrations.Migrations
{
    [DbContext(typeof(LifeGraphDbContext))]
    [Migration("20261005020936_GraphInbox")]
    partial class GraphInbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LifeGraph.Graph.Domain.ChangeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("After")
                        .HasColumnType("jsonb")
                        .HasColumnName("after");

                    b.Property<string>("Before")
                        .HasColumnType("jsonb")
                        .HasColumnName("before");

                    b.Property<Guid?>("CascadeOf")
                        .HasColumnType("uuid")
                        .HasColumnName("cascade_of");

                    b.Property<Guid>("ChangeSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("changeset_id");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("entity_kind");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("operation");

                    b.Property<DateTimeOffset?>("PurgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purged_at");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.HasKey("Id")
                        .HasName("pk_change_entries");

                    b.HasAlternateKey("ChangeSetId", "Id")
                        .HasName("ak_change_entries_changeset_id_id");

                    b.HasIndex("AccountId", "ChangeSetId")
                        .HasDatabaseName("ix_change_entries_account_id_change_set_id");

                    b.HasIndex("AccountId", "EntityId")
                        .HasDatabaseName("ix_change_entries_account_id_entity_id");

                    b.HasIndex("ChangeSetId", "CascadeOf")
                        .HasDatabaseName("ix_change_entries_changeset_id_cascade_of");

                    b.HasIndex("ChangeSetId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("uq_change_entries_changeset_id_sequence");

                    b.ToTable("change_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_change_entries_entity_kind", "entity_kind IN ('node', 'property_definition', 'relation', 'type')");

                            t.HasCheckConstraint("ck_change_entries_operation", "operation IN ('created', 'deleted', 'restored', 'updated')");

                            t.HasCheckConstraint("ck_change_entries_purged_empty", "purged_at IS NULL OR (before IS NULL AND after IS NULL)");

                            t.HasCheckConstraint("ck_change_entries_sequence", "sequence >= 0");
                        });
                });

            modelBuilder.Entity("LifeGraph.Graph.Domain.GraphChangeSet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("ActorKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("actor_kind");

                    b.Property<Guid?>("AgentIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_identity_id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("RevertsChangeSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("reverts_changeset_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Source")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_changesets");

                    b.HasAlternateKey("AccountId", "Id")
                        .HasName("ak_changesets_account_id_id");

                    b.HasIndex("AccountId", "RevertsChangeSetId")
                        .IsUnique()
                        .HasDatabaseName("uq_changesets_account_id_reverts_changeset_id")
                        .HasFilter("reverts_changeset_id IS NOT NULL");

                    b.ToTable("changesets", null, t =>
                        {
                            t.HasCheckConstraint("ck_changesets_actor_kind", "actor_kind IN ('agent_identity', 'human')");

                            t.HasCheckConstraint("ck_changesets_agent_identity", "(actor_kind = 'agent_identity') = (agent_identity_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_changesets_channel", "channel IN ('api', 'import', 'mcp', 'ui')");

                            t.HasCheckConstraint("ck_changesets_status", "status IN ('applied', 'reverted')");
                        });
                });

            modelBuilder.Entity("LifeGraph.Graph.Domain.Node", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("character varying(100000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset?>("InboxEnteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inbox_entered_at");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("properties");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<Guid?>("TypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("type_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_nodes");

                    b.HasAlternateKey("AccountId", "Id")
                        .HasName("ak_nodes_account_id_id");

                    b.HasIndex("Properties")
                        .HasDatabaseName("ix_nodes_properties");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Properties"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Properties"), new[] { "jsonb_path_ops" });

                    b.HasIndex("AccountId", "DeletedAt")
                        .HasDatabaseName("ix_nodes_account_id_deleted_at")
                        .HasFilter("deleted_at IS NOT NULL");

                    b.HasIndex("AccountId", "InboxEnteredAt")
                        .HasDatabaseName("ix_nodes_account_id_inbox_entered_at")
                        .HasFilter("inbox_entered_at IS NOT NULL");

                    b.HasIndex("AccountId", "TypeId")
                        .HasDatabaseName("ix_nodes_account_id_type_id");

                    b.ToTable("nodes", null, t =>
                        {
                            t.HasCheckConstraint("ck_nodes_version", "version >= 1");
                        });
                });

            modelBuilder.Entity("LifeGraph.Graph.Domain.NodeType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_types");

                    b.HasAlternateKey("AccountId", "Id")
                        .HasName("ak_types_account_id_id");

                    b.HasIndex("AccountId", "Name")
                        .IsUnique()
                        .HasDatabaseName("uq_types_account_id_name");

                    b.ToTable("types", (string)null);
                });

            modelBuilder.Entity("LifeGraph.Graph.Domain.PropertyDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("options");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValueKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("value_kind");

                    b.HasKey("Id")
                        .HasName("pk_property_definitions");

                    b.HasAlternateKey("AccountId", "Id")
                        .HasName("ak_property_definitions_account_id_id");

                    b.HasIndex("AccountId", "Name")
                        .IsUnique()
                        .HasDatabaseName("uq_property_definitions_account_id_name");

                    b.ToTable("property_definitions", null, t =>
                        {
                            t.HasCheckConstraint("ck_property_definitions_value_kind", "value_kind IN ('boolean', 'date', 'date_time', 'multi_select', 'number', 'select', 'text', 'url')");
                        });
                });

            modelBuilder.Entity("LifeGraph.Graph.Domain.Relation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("Assertion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("assertion");

                    b.Property<double?>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("kind");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("origin");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("SourceNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_node_id");

                    b.Property<double>("Strength")
                        .HasColumnType("double precision")
                        .HasColumnName("strength");

                    b.Property<Guid>("TargetNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_node_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_relations");

                    b.HasAlternateKey("AccountId", "Id")
                        .HasName("ak_relations_account_id_id");

                    b.HasIndex("AccountId", "DeletedAt")
                        .HasDatabaseName("ix_relations_account_id_deleted_at")
                        .HasFilter("deleted_at IS NOT NULL");

                    b.HasIndex("AccountId", "SourceNodeId")
                        .HasDatabaseName("ix_relations_account_id_source_node_id");

                    b.HasIndex("AccountId", "TargetNodeId")
                        .HasDatabaseName("ix_relations_account_id_target_node_id");

                    b.ToTable("relations", null, t =>
                        {
                            t.HasCheckConstraint("ck_relations_assertion", "assertion IN ('hard', 'soft')");

                            t.HasCheckConstraint("ck_relations_confidence", "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)");

                            t.HasCheckConstraint("ck_relations_not_self", "source_node_id <> target_node_id");

                            t.HasCheckConstraint("ck_relations_origin", "origin IN ('agent', 'import', 'system', 'user')");

                            t.HasCheckConstraint("ck_relations_soft_is_inferred", "assertion = 'hard' OR (origin = 'system' AND confidence IS NOT NULL)");

                            t.HasCheckConstraint("ck_relations_strength", "strength >= 0 AND strength <= 1");
                        });
                });

            modelBuilder.Entity("LifeGraph.Graph.Domain.TypeProperty", b =>
                {
                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("type_id");

                    b.Property<Guid>("PropertyDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_definition_id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("TypeId", "PropertyDefinitionId")
                        .HasName("pk_type_properties");

                    b.HasIndex("AccountId", "PropertyDefinitionId")
                        .HasDatabaseName("ix_type_properties_account_id_property_definition_id");

                    b.HasIndex("AccountId", "TypeId")
                        .HasDatabaseName("ix_type_properties_account_id_type_id");

                    b.ToTable("type_properties", null, t =>
                        {
                            t.HasCheckConstraint("ck_type_properties_position", "position >= 0");
                        });
                });

            modelBuilder.Entity("LifeGraph.Infrastructure.Accounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("LifeGraph.Infrastructure.Identity.LifeGraphUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_account_id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("ix_users_normalized_email");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("ix_users_normalized_user_name");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("LifeGraph.Infrastructure.Jobs.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kind");

                    b.Property<string>("LastError")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_until");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset>("RunAfter")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("run_after");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_jobs");

                    b.HasIndex("LeaseUntil")
                        .HasDatabaseName("ix_jobs_running_lease_until")
                        .HasFilter("status = 'running'");

                    b.HasIndex("RunAfter")
                        .HasDatabaseName("ix_jobs_pending_run_after")
                        .HasFilter("status = 'pending'");

                    b.HasIndex("AccountId", "Kind")
                        .HasDatabaseName("ix_jobs_account_id_kind");

                    b.ToTable("jobs", null, t =>
                        {
                            t.HasCheckConstraint("ck_jobs_attempts", "attempts >= 0");

                            t.HasCheckConstraint("ck_jobs_running_has_lease", "(status = 'running') = (lease_until IS NOT NULL)");

                            t.HasCheckConstraint("ck_jobs_status", "status IN ('dead', 'done', 'pending', 'running')");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claims_user_id");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_logins_user_id");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApplicationType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("application_type");

                    b.Property<string>("ClientId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("text")
                        .HasColumnName("client_secret");

                    b.Property<string>("ClientType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("client_type");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("concurrency_token");

                    b.Property<string>("ConsentType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("consent_type");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("text")
                        .HasColumnName("display_names");

                    b.Property<string>("JsonWebKeySet")
                        .HasColumnType("text")
                        .HasColumnName("json_web_key_set");

                    b.Property<string>("Permissions")
                        .HasColumnType("text")
                        .HasColumnName("permissions");

                    b.Property<string>("PostLogoutRedirectUris")
                        .HasColumnType("text")
                        .HasColumnName("post_logout_redirect_uris");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<string>("RedirectUris")
                        .HasColumnType("text")
                        .HasColumnName("redirect_uris");

                    b.Property<string>("Requirements")
                        .HasColumnType("text")
                        .HasColumnName("requirements");

                    b.Property<string>("Settings")
                        .HasColumnType("text")
                        .HasColumnName("settings");

                    b.HasKey("Id")
                        .HasName("pk_oidc_applications");

                    b.HasIndex("ClientId")
                        .IsUnique()
                        .HasDatabaseName("ix_oidc_applications_client_id");

                    b.ToTable("oidc_applications", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<string>("Scopes")
                        .HasColumnType("text")
                        .HasColumnName("scopes");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("subject");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_oidc_authorizations");

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type")
                        .HasDatabaseName("ix_oidc_authorizations_application_id_status_subject_type");

                    b.ToTable("oidc_authorizations", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreScope<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("concurrency_token");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Descriptions")
                        .HasColumnType("text")
                        .HasColumnName("descriptions");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("text")
                        .HasColumnName("display_names");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<string>("Resources")
                        .HasColumnType("text")
                        .HasColumnName("resources");

                    b.HasKey("Id")
                        .HasName("pk_oidc_scopes");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_oidc_scopes_name");

                    b.ToTable("oidc_scopes", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<Guid?>("AuthorizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("authorization_id");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_date");

                    b.Property<string>("Payload")
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<DateTime?>("RedemptionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("redemption_date");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference_id");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("subject");

                    b.Property<string>("Type")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_oidc_tokens");

                    b.HasIndex("AuthorizationId")
                        .HasDatabaseName("ix_oidc_tokens_authorization_id");

                    b.HasIndex("ReferenceId")
                        .IsUnique()
                        .HasDatabaseName("ix_oidc_tokens_reference_id");

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type")
                        .HasDatabaseName("ix_oidc_tokens_application_id_status_subject_type");

                    b.ToTable("oidc_tokens", (string)null);
                });

            modelBuilder.Entity("LifeGraph.Graph.Domain.ChangeEntry", b =>
                {
                    b.HasOne("LifeGraph.Infrastructure.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_change_entries_account_id");

                    b.HasOne("LifeGraph.Graph.Domain.GraphChangeSet", null)
                        .WithMany("Entries")
                        .HasForeignKey("AccountId", "ChangeSetId")
                        .HasPrincipalKey("AccountId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_change_entries_changeset");

                    b.HasOne("LifeGraph.Graph.Domain.ChangeEntry", null)
                        .WithMany()
                        .HasForeignKey("ChangeSetId", "CascadeOf")
                        .HasPrincipalKey("ChangeSetId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_change_entries_cascade_of");
                });

            modelBuilder.Entity("LifeGraph.Graph.Domain.GraphChangeSet", b =>
                {
                    b.HasOne("LifeGraph.Infrastructure.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_changesets_account_id");

                    b.HasOne("LifeGraph.Graph.Domain.GraphChangeSet", null)
                        .WithMany()
                        .HasForeignKey("AccountId", "RevertsChangeSetId")
                        .HasPrincipalKey("AccountId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_changesets_reverts_changeset");
                });

            modelBuilder.Entity("LifeGraph.Graph.Domain.Node", b =>
                {
                    b.HasOne("LifeGraph.Infrastructure.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_nodes_account_id");

                    b.HasOne("LifeGraph.Graph.Domain.NodeType", null)
                        .WithMany()
                        .HasForeignKey("AccountId", "TypeId")
                        .HasPrincipalKey("AccountId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_nodes_type");
                });

            modelBuilder.Entity("LifeGraph.Graph.Domain.NodeType", b =>
                {
                    b.HasOne("LifeGraph.Infrastructure.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_types_account_id");
                });

            modelBuilder.Entity("LifeGraph.Graph.Domain.PropertyDefinition", b =>
                {
                    b.HasOne("LifeGraph.Infrastructure.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_property_definitions_account_id");
                });

            modelBuilder.Entity("LifeGraph.Graph.Domain.Relation", b =>
                {
                    b.HasOne("LifeGraph.Infrastructure.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_relations_account_id");

                    b.HasOne("LifeGraph.Graph.Domain.Node", null)
                        .WithMany()
                        .HasForeignKey("AccountId", "SourceNodeId")
                        .HasPrincipalKey("AccountId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_relations_source_node");

                    b.HasOne("LifeGraph.Graph.Domain.Node", null)
                        .WithMany()
                        .HasForeignKey("AccountId", "TargetNodeId")
                        .HasPrincipalKey("AccountId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_relations_target_node");
                });

            modelBuilder.Entity("LifeGraph.Graph.Domain.TypeProperty", b =>
                {
                    b.HasOne("LifeGraph.Infrastructure.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_type_properties_account_id");

                    b.HasOne("LifeGraph.Graph.Domain.PropertyDefinition", null)
                        .WithMany()
                        .HasForeignKey("AccountId", "PropertyDefinitionId")
                        .HasPrincipalKey("AccountId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_type_properties_property_definition");

                    b.HasOne("LifeGraph.Graph.Domain.NodeType", null)
                        .WithMany("Properties")
                        .HasForeignKey("AccountId", "TypeId")
                        .HasPrincipalKey("AccountId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_type_properties_type");
                });

            modelBuilder.Entity("LifeGraph.Infrastructure.Identity.LifeGraphUser", b =>
                {
                    b.HasOne("LifeGraph.Infrastructure.Accounts.Account", null)
                        .WithOne()
                        .HasForeignKey("LifeGraph.Infrastructure.Identity.LifeGraphUser", "AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_accounts_account_id");
                });

            modelBuilder.Entity("LifeGraph.Infrastructure.Jobs.Job", b =>
                {
                    b.HasOne("LifeGraph.Infrastructure.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_jobs_account_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("LifeGraph.Infrastructure.Identity.LifeGraphUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claims_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("LifeGraph.Infrastructure.Identity.LifeGraphUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("LifeGraph.Infrastructure.Identity.LifeGraphUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_users_user_id");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization<System.Guid>", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication<System.Guid>", "Application")
                        .WithMany("Authorizations")
                        .HasForeignKey("ApplicationId")
                        .HasConstraintName("fk_oidc_authorizations_oidc_applications_application_id");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken<System.Guid>", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication<System.Guid>", "Application")
                        .WithMany("Tokens")
                        .HasForeignKey("ApplicationId")
                        .HasConstraintName("fk_oidc_tokens_oidc_applications_application_id");

                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization<System.Guid>", "Authorization")
                        .WithMany("Tokens")
                        .HasForeignKey("AuthorizationId")
                        .HasConstraintName("fk_oidc_tokens_oidc_authorizations_authorization_id");

                    b.Navigation("Application");

                    b.Navigation("Authorization");
                });

            modelBuilder.Entity("LifeGraph.Graph.Domain.GraphChangeSet", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("LifeGraph.Graph.Domain.NodeType", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication<System.Guid>", b =>
                {
                    b.Navigation("Authorizations");

                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization<System.Guid>", b =>
                {
                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
